/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creditsdebits;

/**
 *
 * @author John
 */
public class CreditDebit extends javax.swing.JFrame {

    /**
     * Creates new form CreditDebit
     */
    public CreditDebit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtMitAcres = new javax.swing.JTextField();
        lblMAcres = new javax.swing.JLabel();
        jtxtDevAcres = new javax.swing.JTextField();
        lblDAcres = new javax.swing.JLabel();
        jtxtMDivider = new javax.swing.JTextField();
        lblDAcres1 = new javax.swing.JLabel();
        jtxtDMultiplier = new javax.swing.JTextField();
        lblDAcres2 = new javax.swing.JLabel();
        jtxtNumCrdtsRemain = new javax.swing.JTextField();
        lblNoCrdtsRemain = new javax.swing.JLabel();
        jtxtValPerCrdt = new javax.swing.JTextField();
        lblValuePerCrdt = new javax.swing.JLabel();
        jtxtValCrdtsRemain = new javax.swing.JTextField();
        lblNoCrdtsRemain1 = new javax.swing.JLabel();
        lblMitBnkCalc = new javax.swing.JLabel();
        jbttnCalculate = new javax.swing.JButton();
        jbttnClear = new javax.swing.JButton();
        jbttnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtMitAcres.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtMitAcres.setForeground(new java.awt.Color(0, 204, 0));
        jtxtMitAcres.setToolTipText("");

        lblMAcres.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMAcres.setText("Mitigation Site (Acres)");
        lblMAcres.setToolTipText("");

        jtxtDevAcres.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtDevAcres.setForeground(new java.awt.Color(204, 0, 51));
        jtxtDevAcres.setToolTipText("");

        lblDAcres.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDAcres.setText("Development Site (Acres)");
        lblDAcres.setToolTipText("");

        jtxtMDivider.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtMDivider.setForeground(new java.awt.Color(0, 204, 0));
        jtxtMDivider.setToolTipText("");

        lblDAcres1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDAcres1.setText("Mitigation Divider");
        lblDAcres1.setToolTipText("");

        jtxtDMultiplier.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtDMultiplier.setForeground(new java.awt.Color(204, 0, 0));
        jtxtDMultiplier.setToolTipText("");

        lblDAcres2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDAcres2.setText("Development Multiplier");
        lblDAcres2.setToolTipText("");

        jtxtNumCrdtsRemain.setEditable(false);
        jtxtNumCrdtsRemain.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jtxtNumCrdtsRemain.setToolTipText("");

        lblNoCrdtsRemain.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNoCrdtsRemain.setText("Number of Credits Remaining");
        lblNoCrdtsRemain.setToolTipText("");

        jtxtValPerCrdt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtValPerCrdt.setToolTipText("");

        lblValuePerCrdt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblValuePerCrdt.setText("Price Per Credit ($)");
        lblValuePerCrdt.setToolTipText("");

        jtxtValCrdtsRemain.setEditable(false);
        jtxtValCrdtsRemain.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jtxtValCrdtsRemain.setToolTipText("");

        lblNoCrdtsRemain1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNoCrdtsRemain1.setText("Value of Remaining Credits ($)");
        lblNoCrdtsRemain1.setToolTipText("");

        lblMitBnkCalc.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblMitBnkCalc.setForeground(new java.awt.Color(0, 102, 102));
        lblMitBnkCalc.setText("Mitigation Bank Credit / Debit Calculator");
        lblMitBnkCalc.setToolTipText("");

        jbttnCalculate.setBackground(new java.awt.Color(255, 255, 255));
        jbttnCalculate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbttnCalculate.setForeground(new java.awt.Color(0, 51, 102));
        jbttnCalculate.setText("Calculate");
        jbttnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnCalculateActionPerformed(evt);
            }
        });

        jbttnClear.setBackground(new java.awt.Color(255, 255, 255));
        jbttnClear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbttnClear.setForeground(new java.awt.Color(255, 0, 0));
        jbttnClear.setText("Clear");
        jbttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnClearActionPerformed(evt);
            }
        });

        jbttnExit.setBackground(new java.awt.Color(255, 255, 255));
        jbttnExit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jbttnExit.setText("Exit");
        jbttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblMitBnkCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtValCrdtsRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblNoCrdtsRemain1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtValPerCrdt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblValuePerCrdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtNumCrdtsRemain, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblNoCrdtsRemain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtDMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblDAcres2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtxtMitAcres, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtxtMDivider, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(lblDAcres1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtDevAcres, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMAcres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDAcres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbttnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jbttnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMitBnkCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMitAcres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMAcres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtDevAcres)
                    .addComponent(lblDAcres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMDivider)
                    .addComponent(lblDAcres1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDMultiplier)
                    .addComponent(lblDAcres2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtValPerCrdt)
                    .addComponent(lblValuePerCrdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNumCrdtsRemain)
                    .addComponent(lblNoCrdtsRemain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtValCrdtsRemain)
                    .addComponent(lblNoCrdtsRemain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbttnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbttnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnClearActionPerformed
        // TODO add your handling code here:
        jtxtDevAcres.setText("");
        jtxtDMultiplier.setText("");
        jtxtMitAcres.setText("");
        jtxtMDivider.setText("");
        jtxtNumCrdtsRemain.setText("");
        jtxtValPerCrdt.setText("");
        jtxtValCrdtsRemain.setText("");
        
        
        
    }//GEN-LAST:event_jbttnClearActionPerformed

    private void jbttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbttnExitActionPerformed

    private void jbttnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnCalculateActionPerformed
        // TODO add your handling code here:
        Double devDebits = 0.0;
        Double devAcres = 0.0;
        Double devMult = 0.0;
        
        Double mitCredits = 0.0;
        Double mitAcres = 0.0;
        Double mitDiv = 0.0;
        
        Double netCredits = 0.0;
        Double priceCrdt = 0.0;
        Double valRemainCrdt = 0.0;
        
        devAcres = Double.parseDouble(jtxtDevAcres.getText());
        devMult = Double.parseDouble(jtxtDMultiplier.getText());
        
        devDebits = devAcres * devMult;
        
        mitAcres = Double.parseDouble(jtxtMitAcres.getText());
        mitDiv = Double.parseDouble(jtxtMDivider.getText());
        
        mitCredits = mitAcres / mitDiv;
        
        netCredits = mitCredits - devDebits;
        priceCrdt = Double.parseDouble(jtxtValPerCrdt.getText());
        valRemainCrdt = priceCrdt * netCredits;
        
        jtxtNumCrdtsRemain.setText(String.valueOf(netCredits));
        jtxtValCrdtsRemain.setText(String.valueOf(valRemainCrdt));
        
        
    }//GEN-LAST:event_jbttnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditDebit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditDebit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditDebit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditDebit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditDebit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbttnCalculate;
    private javax.swing.JButton jbttnClear;
    private javax.swing.JButton jbttnExit;
    private javax.swing.JTextField jtxtDMultiplier;
    private javax.swing.JTextField jtxtDevAcres;
    private javax.swing.JTextField jtxtMDivider;
    private javax.swing.JTextField jtxtMitAcres;
    private javax.swing.JTextField jtxtNumCrdtsRemain;
    private javax.swing.JTextField jtxtValCrdtsRemain;
    private javax.swing.JTextField jtxtValPerCrdt;
    private javax.swing.JLabel lblDAcres;
    private javax.swing.JLabel lblDAcres1;
    private javax.swing.JLabel lblDAcres2;
    private javax.swing.JLabel lblMAcres;
    private javax.swing.JLabel lblMitBnkCalc;
    private javax.swing.JLabel lblNoCrdtsRemain;
    private javax.swing.JLabel lblNoCrdtsRemain1;
    private javax.swing.JLabel lblValuePerCrdt;
    // End of variables declaration//GEN-END:variables
}
