/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rasterappclass;

/**
 *
 * @author John
 */
public class RasterAppForm extends javax.swing.JFrame {

    /**
     * Creates new form RasterAppForm
     */
    public RasterAppForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtP1T1 = new javax.swing.JTextField();
        txtP1T2 = new javax.swing.JTextField();
        txtP1T3 = new javax.swing.JTextField();
        txtP1T4 = new javax.swing.JTextField();
        txtP1T5 = new javax.swing.JTextField();
        txtP1T6 = new javax.swing.JTextField();
        txtP1T7 = new javax.swing.JTextField();
        txtP1T8 = new javax.swing.JTextField();
        txtP1T9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtP2T1 = new javax.swing.JTextField();
        txtP2T2 = new javax.swing.JTextField();
        txtP2T3 = new javax.swing.JTextField();
        txtP2T4 = new javax.swing.JTextField();
        txtP2T5 = new javax.swing.JTextField();
        txtP2T6 = new javax.swing.JTextField();
        txtP2T7 = new javax.swing.JTextField();
        txtP2T8 = new javax.swing.JTextField();
        txtP2T9 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtP3T1 = new javax.swing.JTextField();
        txtP3T2 = new javax.swing.JTextField();
        txtP3T3 = new javax.swing.JTextField();
        txtP3T4 = new javax.swing.JTextField();
        txtP3T5 = new javax.swing.JTextField();
        txtP3T6 = new javax.swing.JTextField();
        txtP3T7 = new javax.swing.JTextField();
        txtP3T8 = new javax.swing.JTextField();
        txtP3T9 = new javax.swing.JTextField();
        bttnCalc = new javax.swing.JButton();
        bttnClear = new javax.swing.JButton();
        bttnExit = new javax.swing.JButton();
        bttnAdd = new javax.swing.JButton();
        javax.swing.JButton bttnSubtract = new javax.swing.JButton();
        bttnAverage = new javax.swing.JButton();
        bttnAvgAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        txtP1T1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T1.setForeground(new java.awt.Color(255, 0, 0));
        txtP1T1.setToolTipText("");

        txtP1T2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T2.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T2.setToolTipText("");

        txtP1T3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T3.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T3.setToolTipText("");

        txtP1T4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T4.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T4.setToolTipText("");

        txtP1T5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T5.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T5.setToolTipText("");

        txtP1T6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T6.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T6.setToolTipText("");

        txtP1T7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T7.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T7.setToolTipText("");

        txtP1T8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T8.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T8.setToolTipText("");

        txtP1T9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP1T9.setForeground(new java.awt.Color(255, 51, 51));
        txtP1T9.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtP1T4)
                            .addComponent(txtP1T1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtP1T2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(txtP1T5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtP1T3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(txtP1T6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtP1T7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtP1T8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP1T9, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP1T1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(txtP1T3)
                    .addComponent(txtP1T2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP1T4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(txtP1T6)
                    .addComponent(txtP1T5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtP1T9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtP1T8)
                        .addComponent(txtP1T7, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        txtP2T1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T1.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T1.setToolTipText("");

        txtP2T2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T2.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T2.setToolTipText("");

        txtP2T3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T3.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T3.setToolTipText("");

        txtP2T4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T4.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T4.setToolTipText("");

        txtP2T5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T5.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T5.setToolTipText("");

        txtP2T6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T6.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T6.setToolTipText("");

        txtP2T7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T7.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T7.setToolTipText("");

        txtP2T8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T8.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T8.setToolTipText("");

        txtP2T9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP2T9.setForeground(new java.awt.Color(0, 0, 102));
        txtP2T9.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP2T7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(txtP2T4)
                    .addComponent(txtP2T1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP2T8, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtP2T5)
                    .addComponent(txtP2T2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtP2T3)
                    .addComponent(txtP2T9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtP2T6))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP2T1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(txtP2T2)
                    .addComponent(txtP2T3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP2T4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(txtP2T5)
                    .addComponent(txtP2T6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP2T7, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(txtP2T8)
                    .addComponent(txtP2T9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        txtP3T1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T1.setToolTipText("");

        txtP3T2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T2.setToolTipText("");

        txtP3T3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T3.setToolTipText("");

        txtP3T4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T4.setToolTipText("");

        txtP3T5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T5.setToolTipText("");

        txtP3T6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T6.setToolTipText("");

        txtP3T7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T7.setToolTipText("");

        txtP3T8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T8.setToolTipText("");

        txtP3T9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtP3T9.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP3T7, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(txtP3T4)
                    .addComponent(txtP3T1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP3T8, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(txtP3T2)
                    .addComponent(txtP3T5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP3T9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(txtP3T6)
                    .addComponent(txtP3T3))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP3T1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtP3T2)
                    .addComponent(txtP3T3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP3T4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtP3T5)
                    .addComponent(txtP3T6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtP3T7, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(txtP3T8)
                    .addComponent(txtP3T9))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bttnCalc.setBackground(new java.awt.Color(255, 255, 204));
        bttnCalc.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        bttnCalc.setForeground(new java.awt.Color(0, 0, 204));
        bttnCalc.setText("Multiply Cells");
        bttnCalc.setToolTipText("");
        bttnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCalcActionPerformed(evt);
            }
        });

        bttnClear.setBackground(new java.awt.Color(255, 255, 204));
        bttnClear.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        bttnClear.setForeground(new java.awt.Color(204, 0, 0));
        bttnClear.setText("Clear");
        bttnClear.setToolTipText("");
        bttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClearActionPerformed(evt);
            }
        });

        bttnExit.setBackground(new java.awt.Color(255, 255, 204));
        bttnExit.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        bttnExit.setForeground(new java.awt.Color(0, 102, 102));
        bttnExit.setText("Exit");
        bttnExit.setToolTipText("");
        bttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitActionPerformed(evt);
            }
        });

        bttnAdd.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        bttnAdd.setForeground(new java.awt.Color(204, 0, 0));
        bttnAdd.setText("Add Cells");
        bttnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddActionPerformed(evt);
            }
        });

        bttnSubtract.setBackground(new java.awt.Color(0, 0, 51));
        bttnSubtract.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bttnSubtract.setForeground(new java.awt.Color(255, 255, 255));
        bttnSubtract.setText("Subtract Cells");
        bttnSubtract.setToolTipText("");
        bttnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSubtractActionPerformed(evt);
            }
        });

        bttnAverage.setBackground(new java.awt.Color(255, 255, 255));
        bttnAverage.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        bttnAverage.setText("Average Cells");
        bttnAverage.setToolTipText("");
        bttnAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAverageActionPerformed(evt);
            }
        });

        bttnAvgAll.setBackground(new java.awt.Color(255, 255, 204));
        bttnAvgAll.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        bttnAvgAll.setForeground(new java.awt.Color(0, 204, 204));
        bttnAvgAll.setText("Average All Cells");
        bttnAvgAll.setToolTipText("");
        bttnAvgAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAvgAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttnAvgAll, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bttnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnSubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bttnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bttnAvgAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCalcActionPerformed
        // TODO add your handling code here:
        
        double a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, zz;
        
        a = Double.parseDouble(txtP1T1.getText());
        b = Double.parseDouble(txtP1T2.getText());
        c = Double.parseDouble(txtP1T3.getText());
        d = Double.parseDouble(txtP1T4.getText());
        e = Double.parseDouble(txtP1T5.getText());
        f = Double.parseDouble(txtP1T6.getText());
        g = Double.parseDouble(txtP1T7.getText());
        h = Double.parseDouble(txtP1T8.getText());
        i = Double.parseDouble(txtP1T9.getText());

        j = Double.parseDouble(txtP2T1.getText());
        k = Double.parseDouble(txtP2T2.getText());
        l = Double.parseDouble(txtP2T3.getText());
        m = Double.parseDouble(txtP2T4.getText());
        n = Double.parseDouble(txtP2T5.getText());
        o = Double.parseDouble(txtP2T6.getText());
        p = Double.parseDouble(txtP2T7.getText());
        q = Double.parseDouble(txtP2T8.getText());
        r = Double.parseDouble(txtP2T9.getText());
        
        s = a * j; t = b * k; u = c * l;
        v = d * m; w = e * n; x = f * o;
        y = g * p; z = h * q; zz = i * r;
        
       txtP3T1.setText(String.valueOf(s));
       txtP3T2.setText(String.valueOf(t));
       txtP3T3.setText(String.valueOf(u));
       txtP3T4.setText(String.valueOf(v));
       txtP3T5.setText(String.valueOf(w));
       txtP3T6.setText(String.valueOf(x));
       txtP3T7.setText(String.valueOf(y));;
       txtP3T8.setText(String.valueOf(z));
       txtP3T9.setText(String.valueOf(zz));    
    }//GEN-LAST:event_bttnCalcActionPerformed

    private void bttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClearActionPerformed
        // TODO add your handling code here:
        txtP1T1.setText("");
        txtP1T2.setText("");
        txtP1T3.setText("");
        txtP1T4.setText("");
        txtP1T5.setText("");
        txtP1T6.setText("");
        txtP1T7.setText("");
        txtP1T8.setText("");
        txtP1T9.setText("");
        txtP2T1.setText("");
        txtP2T2.setText("");
        txtP2T3.setText("");
        txtP2T4.setText("");
        txtP2T5.setText("");
        txtP2T6.setText("");
        txtP2T7.setText("");
        txtP2T8.setText("");
        txtP2T9.setText("");
        txtP3T1.setText("");
        txtP3T2.setText("");
        txtP3T3.setText("");
        txtP3T4.setText("");
        txtP3T5.setText("");
        txtP3T6.setText("");
        txtP3T7.setText("");
        txtP3T8.setText("");
        txtP3T9.setText("");               
    }//GEN-LAST:event_bttnClearActionPerformed

    private void bttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bttnExitActionPerformed

    private void bttnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddActionPerformed
        // TODO add your handling code here:
          double a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, zz;
        
        a = Double.parseDouble(txtP1T1.getText());
        b = Double.parseDouble(txtP1T2.getText());
        c = Double.parseDouble(txtP1T3.getText());
        d = Double.parseDouble(txtP1T4.getText());
        e = Double.parseDouble(txtP1T5.getText());
        f = Double.parseDouble(txtP1T6.getText());
        g = Double.parseDouble(txtP1T7.getText());
        h = Double.parseDouble(txtP1T8.getText());
        i = Double.parseDouble(txtP1T9.getText());

        j = Double.parseDouble(txtP2T1.getText());
        k = Double.parseDouble(txtP2T2.getText());
        l = Double.parseDouble(txtP2T3.getText());
        m = Double.parseDouble(txtP2T4.getText());
        n = Double.parseDouble(txtP2T5.getText());
        o = Double.parseDouble(txtP2T6.getText());
        p = Double.parseDouble(txtP2T7.getText());
        q = Double.parseDouble(txtP2T8.getText());
        r = Double.parseDouble(txtP2T9.getText());
        
        s = a + j; t = b + k; u = c + l;
        v = d + m; w = e + n; x = f + o;
        y = g + p; z = h + q; zz = i + r;
        
       txtP3T1.setText(String.valueOf(s));
       txtP3T2.setText(String.valueOf(t));
       txtP3T3.setText(String.valueOf(u));
       txtP3T4.setText(String.valueOf(v));
       txtP3T5.setText(String.valueOf(w));
       txtP3T6.setText(String.valueOf(x));
       txtP3T7.setText(String.valueOf(y));;
       txtP3T8.setText(String.valueOf(z));
       txtP3T9.setText(String.valueOf(zz));    
        
    }//GEN-LAST:event_bttnAddActionPerformed

    private void bttnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSubtractActionPerformed
        // TODO add your handling code here:
         double a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, zz;
        
        a = Double.parseDouble(txtP1T1.getText());
        b = Double.parseDouble(txtP1T2.getText());
        c = Double.parseDouble(txtP1T3.getText());
        d = Double.parseDouble(txtP1T4.getText());
        e = Double.parseDouble(txtP1T5.getText());
        f = Double.parseDouble(txtP1T6.getText());
        g = Double.parseDouble(txtP1T7.getText());
        h = Double.parseDouble(txtP1T8.getText());
        i = Double.parseDouble(txtP1T9.getText());

        j = Double.parseDouble(txtP2T1.getText());
        k = Double.parseDouble(txtP2T2.getText());
        l = Double.parseDouble(txtP2T3.getText());
        m = Double.parseDouble(txtP2T4.getText());
        n = Double.parseDouble(txtP2T5.getText());
        o = Double.parseDouble(txtP2T6.getText());
        p = Double.parseDouble(txtP2T7.getText());
        q = Double.parseDouble(txtP2T8.getText());
        r = Double.parseDouble(txtP2T9.getText());
        
        s = a - j; t = b - k; u = c - l;
        v = d - m; w = e - n; x = f - o;
        y = g - p; z = h - q; zz = i - r;
        
       txtP3T1.setText(String.valueOf(s));
       txtP3T2.setText(String.valueOf(t));
       txtP3T3.setText(String.valueOf(u));
       txtP3T4.setText(String.valueOf(v));
       txtP3T5.setText(String.valueOf(w));
       txtP3T6.setText(String.valueOf(x));
       txtP3T7.setText(String.valueOf(y));;
       txtP3T8.setText(String.valueOf(z));
       txtP3T9.setText(String.valueOf(zz)); 
    }//GEN-LAST:event_bttnSubtractActionPerformed

    private void bttnAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAverageActionPerformed
        // TODO add your handling code here:
         double a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, zz;
       
        
        a = Double.parseDouble(txtP1T1.getText());
        b = Double.parseDouble(txtP1T2.getText());
        c = Double.parseDouble(txtP1T3.getText());
        d = Double.parseDouble(txtP1T4.getText());
        e = Double.parseDouble(txtP1T5.getText());
        f = Double.parseDouble(txtP1T6.getText());
        g = Double.parseDouble(txtP1T7.getText());
        h = Double.parseDouble(txtP1T8.getText());
        i = Double.parseDouble(txtP1T9.getText());

        j = Double.parseDouble(txtP2T1.getText());
        k = Double.parseDouble(txtP2T2.getText());
        l = Double.parseDouble(txtP2T3.getText());
        m = Double.parseDouble(txtP2T4.getText());
        n = Double.parseDouble(txtP2T5.getText());
        o = Double.parseDouble(txtP2T6.getText());
        p = Double.parseDouble(txtP2T7.getText());
        q = Double.parseDouble(txtP2T8.getText());
        r = Double.parseDouble(txtP2T9.getText());
        
        s = (a + j)/2; t = (b + k)/2; u = (c + l)/2;
        v = (d + m)/2; w = (e + n)/2; x = (f + o)/2;
        y = (g + p)/2; z = (h + q)/2; zz = (i + r)/2;
        
       txtP3T1.setText(String.valueOf(s));
       txtP3T2.setText(String.valueOf(t));
       txtP3T3.setText(String.valueOf(u));
       txtP3T4.setText(String.valueOf(v));
       txtP3T5.setText(String.valueOf(w));
       txtP3T6.setText(String.valueOf(x));
       txtP3T7.setText(String.valueOf(y));;
       txtP3T8.setText(String.valueOf(z));
       txtP3T9.setText(String.valueOf(zz));     
    }//GEN-LAST:event_bttnAverageActionPerformed

    private void bttnAvgAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAvgAllActionPerformed
        // TODO add your handling code here:
        
          double a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, zz;
          double za, zb, zc, zd, ze, zf, zg, zh, zi;
          
        a = Double.parseDouble(txtP1T1.getText());
        b = Double.parseDouble(txtP1T2.getText());
        c = Double.parseDouble(txtP1T3.getText());
        d = Double.parseDouble(txtP1T4.getText());
        e = Double.parseDouble(txtP1T5.getText());
        f = Double.parseDouble(txtP1T6.getText());
        g = Double.parseDouble(txtP1T7.getText());
        h = Double.parseDouble(txtP1T8.getText());
        i = Double.parseDouble(txtP1T9.getText());

        j = Double.parseDouble(txtP2T1.getText());
        k = Double.parseDouble(txtP2T2.getText());
        l = Double.parseDouble(txtP2T3.getText());
        m = Double.parseDouble(txtP2T4.getText());
        n = Double.parseDouble(txtP2T5.getText());
        o = Double.parseDouble(txtP2T6.getText());
        p = Double.parseDouble(txtP2T7.getText());
        q = Double.parseDouble(txtP2T8.getText());
        r = Double.parseDouble(txtP2T9.getText());
        
        s = (a + j)/2; t = (b + k)/2; u = (c + l)/2;
        v = (d + m)/2; w = (e + n)/2; x = (f + o)/2;
        y = (g + p)/2; z = (h + q)/2; zz = (i + r)/2;
            
        za = (s + t + u + v + w + x + y + z + zz) / 9;
        zb = (s + t + u + v + w + x + y + z + zz) / 9;
        zc = (s + t + u + v + w + x + y + z + zz) / 9;
        zd = (s + t + u + v + w + x + y + z + zz) / 9;
        ze = (s + t + u + v + w + x + y + z + zz) / 9;
        zf = (s + t + u + v + w + x + y + z + zz) / 9;
        zg = (s + t + u + v + w + x + y + z + zz) / 9;
        zh = (s + t + u + v + w + x + y + z + zz) / 9;
        zi = (s + t + u + v + w + x + y + z + zz) / 9;
        
       txtP3T1.setText(String.valueOf(za));
       txtP3T2.setText(String.valueOf(zb));
       txtP3T3.setText(String.valueOf(zc));
       txtP3T4.setText(String.valueOf(zd));
       txtP3T5.setText(String.valueOf(ze));
       txtP3T6.setText(String.valueOf(zf));
       txtP3T7.setText(String.valueOf(zg));;
       txtP3T8.setText(String.valueOf(zh));
       txtP3T9.setText(String.valueOf(zi)); 
    }//GEN-LAST:event_bttnAvgAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RasterAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RasterAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RasterAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RasterAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RasterAppForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAdd;
    private javax.swing.JButton bttnAverage;
    private javax.swing.JButton bttnAvgAll;
    private javax.swing.JButton bttnCalc;
    private javax.swing.JButton bttnClear;
    private javax.swing.JButton bttnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtP1T1;
    private javax.swing.JTextField txtP1T2;
    private javax.swing.JTextField txtP1T3;
    private javax.swing.JTextField txtP1T4;
    private javax.swing.JTextField txtP1T5;
    private javax.swing.JTextField txtP1T6;
    private javax.swing.JTextField txtP1T7;
    private javax.swing.JTextField txtP1T8;
    private javax.swing.JTextField txtP1T9;
    private javax.swing.JTextField txtP2T1;
    private javax.swing.JTextField txtP2T2;
    private javax.swing.JTextField txtP2T3;
    private javax.swing.JTextField txtP2T4;
    private javax.swing.JTextField txtP2T5;
    private javax.swing.JTextField txtP2T6;
    private javax.swing.JTextField txtP2T7;
    private javax.swing.JTextField txtP2T8;
    private javax.swing.JTextField txtP2T9;
    private javax.swing.JTextField txtP3T1;
    private javax.swing.JTextField txtP3T2;
    private javax.swing.JTextField txtP3T3;
    private javax.swing.JTextField txtP3T4;
    private javax.swing.JTextField txtP3T5;
    private javax.swing.JTextField txtP3T6;
    private javax.swing.JTextField txtP3T7;
    private javax.swing.JTextField txtP3T8;
    private javax.swing.JTextField txtP3T9;
    // End of variables declaration//GEN-END:variables
}
